package constants

const (
	ADD_COURSE_OFFERING = "ADD-COURSE-OFFERING"
	REGISTER            = "REGISTER"
	ALLOT_COURSE        = "ALLOT-COURSE"
	COURSE_CANCELED     = "COURSE_CANCELED"
	COURSE_FULL_ERROR   = "COURSE_FULL_ERROR"
	CANCEL              = "CANCEL"
	CANCEL_ACCEPTED     = "CANCEL_ACCEPTED"
	CANCEL_REJECTED     = "CANCEL_REJECTED"
	INPUT_DATA_ERROR    = "INPUT_DATA_ERROR"
	OFFERING            = "OFFERING"
	REG_COURSE          = "REG-COURSE"
	ACCEPTED            = "ACCEPTED"
)
